### ISSUE TITLE
Error: Cannot find module 'angular-cli/plugins/karma'

### ISSUE THREAD

**Issue by FanMix** [dotnet-state-machine/stateless#127]
C:\Dev\myproj\primer-master> ng test
Your global Angular CLI version (1.0.0-beta.31) is greater than your local
version (1.0.0-beta.30). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
13 02 2017 17:19:12.422:ERROR [config]: Error in config file!
 { Error: Cannot find module 'angular-cli/plugins/karma'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (C:\Dev\myproj\primer-master\karma.conf.js:12:7)
    at Object.parseConfig (C:\Dev\myproj\primer-master\node_modules\karma\lib\config.js:396:5)
    at new Server (C:\Dev\myproj\primer-master\node_modules\karma\lib\server.js:56:20)
    at C:\Dev\myproj\primer-master\node_modules\@angular\cli\tasks\test.js:26:31
    at Class.run (C:\Dev\myproj\primer-master\node_modules\@angular\cli\tasks\test.js:10:16)
    at Class.run (C:\Dev\myproj\primer-master\node_modules\@angular\cli\commands\test.js:29:25)
    at Class.<anonymous> (C:\Dev\myproj\primer-master\node_modules\@angular\cli\ember-cli\lib\models\command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7) code: 'MODULE_NOT_FOUND' }

**Comment by nblumhardt** [comment]
Hi @FanMix - looks like you raised this in the wrong repository. Cheers!

**Comment by FanMix** [comment]
Oops. You are right. Thanks.
