### ISSUE TITLE
MultipleTransitions Not Permitted Exception when Multiple PermitIf guard return false

### ISSUE THREAD

**Issue by trgrote** [dotnet-state-machine/stateless#229]
I have an example where a state is configured with two PermitIf transitions.  They are mutually exclusive and can never both be true.  I also have a handler for UnHandledTrigger so what would normally be an exception, instead gets handled with a callback.
 
```csharp
[Fact]
public void NoExceptionWhenPermitIfHasMultipleExclusiveGuardsBothFalse()
{
    var sm = new StateMachine<State, Trigger>(State.A);
    bool onUnhandledTriggerWasCalled = false;
    sm.OnUnhandledTrigger((s, t) => { onUnhandledTriggerWasCalled = true; });  // NEVER CALLED
    int i = 0;
    sm.Configure(State.A)
        .PermitIf(Trigger.X, State.B, () => i == 2)
        .PermitIf(Trigger.X, State.C, () => i == 1);

    sm.Fire(Trigger.X);  // THROWS EXCEPTION

    Assert.True(onUnhandledTriggerWasCalled, "OnUnhandledTrigger was called");
    Assert.Equal(sm.State, State.A);
}
```
However, when I send a trigger while both guard conditions are false, instead of getting the UnHandled callback, I get an Un-OnUnHandled? exception that indicates there is ambiguity between possible states.  

Here is the Exception stack:
```csharp
System.InvalidOperationException : Multiple permitted exit transitions are configured from state 'A' for trigger 'X'. Guard clauses must be mutually exclusive.
   at Stateless.StateMachine`2.StateRepresentation.TryFindLocalHandlerResult(TTrigger trigger, IEnumerable`1 results, Func`2 filter) in C:\Users\grotet\Code\stateless\src\Stateless\StateRepresentation.cs:line 87
   at Stateless.StateMachine`2.StateRepresentation.TryFindLocalHandler(TTrigger trigger, Object[] args, TriggerBehaviourResult& handlerResult) in C:\Users\grotet\Code\stateless\src\Stateless\StateRepresentation.cs:line 71
   at Stateless.StateMachine`2.StateRepresentation.TryFindHandler(TTrigger trigger, Object[] args, TriggerBehaviourResult& handler) in C:\Users\grotet\Code\stateless\src\Stateless\StateRepresentation.cs:line 55
   at Stateless.StateMachine`2.InternalFireOne(TTrigger trigger, Object[] args) in C:\Users\grotet\Code\stateless\src\Stateless\StateMachine.cs:line 273
   at Stateless.StateMachine`2.InternalFire(TTrigger trigger, Object[] args) in C:\Users\grotet\Code\stateless\src\Stateless\StateMachine.cs:line 251
   at Stateless.StateMachine`2.Fire(TTrigger trigger) in C:\Users\grotet\Code\stateless\src\Stateless\StateMachine.cs:line 151
   at Stateless.Tests.StateMachineFixture.NoExceptionWhenPermitIfHasMultipleExclusiveGuardsBothFalse() in C:\Users\grotet\Code\stateless\test\Stateless.Tests\StateMachineFixture.cs:line 592
```
Obviously, that exception isn't accurate as there is zero ambiguity on what should happen.  On top of that issue, the unhandled trigger should be sent to my handler and not throw an exception.

This is especially strange, because with just one PermitIf, the check works as expected:
```csharp
...
    sm.Configure(State.A)
        .PermitIf(Trigger.X, State.C, () => i == 1);

    sm.Fire(Trigger.X);  // This shouldn't throw an exception and we should just ignore it

    Assert.True(onUnhandledTriggerWasCalled, "OnUnhandledTrigger was called");
    Assert.Equal(sm.State, State.A);
}
```
To me, this situation should be treated like a normal unhandled trigger, but it's instead treated like a state machine configuration error - which it's not.

**Comment by HenningNT** [comment]
I think something isn't right in TryFindLocalHandlerResult...

**Comment by HenningNT** [comment]
I changed TryFindLocalHandler to 

            bool TryFindLocalHandler(TTrigger trigger, object[] args, out TriggerBehaviourResult handlerResult)
            {
                // Get list of candidate trigger handlers
                if (!_triggerBehaviours.TryGetValue(trigger, out ICollection<TriggerBehaviour> possible))
                {
                    handlerResult = null;
                    return false;
                }

                // Remove those that have unmet guard conditions
                // Guard functions are executed here
                var actual = possible
                    .Select(h => new TriggerBehaviourResult(h, h.UnmetGuardConditions(args)))
                    .Where(g => g.UnmetGuardConditions.Count == 0)
                    .ToArray();

                // Find a handler for the trigger
                handlerResult = TryFindLocalHandlerResult(trigger, actual, r => !r.UnmetGuardConditions.Any())
                    ?? TryFindLocalHandlerResult(trigger, actual, r => r.UnmetGuardConditions.Any());

                if (handlerResult == null) return false;

                return !handlerResult.UnmetGuardConditions.Any();
            }

This makes your example test pass, but fails three new tests...

**Comment by trgrote** [comment]
All the unit tests are working for me.  Which ones did you say were failing?

**Comment by trgrote** [comment]
But yes. Looks good to me
